### ISSUE TITLE
SLA / Time to Remediate Policy as Code

### ISSUE THREAD

**Issue by GeekMasher** [GeekMasher/advanced-security-compliance#13]
### Description

It would be awesome to define a "time to remediate" or SLA (service-level agreement) policy that only brings up an alert if certain criteria is meet. By default, this mode should not be present and can be enabled by the policy.

**Example Scenario**

- Dependabot opens a High security issue
- I define that High Security issues have to be fixed within 1 day
- Before then, the Action can be run and does not break the workflow
- After 1 day, the Action with start breaking the workflow

### Propose Solution

```yaml
# Applies everywhere
general:
  remediate:
    errors: 7
    warnings: 30
    all: 90

codescanning:
  # Applies only to codescanning
  remediate:
    # Break when detected when set to `0`
    errors: 0
  # ...
  conditions:
    ids:
      - */sql-injection
```

### [optional] Alternative Solutions

Other suggestions are welcome.
