### ISSUE TITLE
Configuration File

### ISSUE THREAD

**Issue by GeekMasher** [GeekMasher/advanced-security-compliance#22]
### Description

We need a configuration file so that each repository can use the same configuration file for an entire organisation.

### Propose Solution

We need a simple yet powerful configuration file.
These settings are replaced by CLI / Actions arguments or replaced entirely.

```yml
name: "Standard Configuration"

policy:
  repository: GeekMasher/advanced-security-compliance
  path: example/path/policy.yml
  branch: main

enabled:
  # Default: true
  code-scanning: false
  dependabot: true
  secret-scanning: false

reporting:
  issues:
    # ...
```

### [optional] Alternative Solutions

NA
