### ISSUE TITLE
`policy-branch` argument does not work as expected

### ISSUE THREAD

**Issue by jlouros** [GeekMasher/advanced-security-compliance#27]
**Describe the bug**
Action parameter `policy-branch` is not working as intended. No matter what value is set, it seems to be always using the default branch.

**To Reproduce**
Setup action with the following params:
```yaml
security-compliance:
    runs-on: ubuntu-latest
    needs:
      - codeql
    steps:
      - name: Advance Security Compliance Action
        uses: GeekMasher/advanced-security-compliance@v1.3
        with:
          token: ${{ secrets.GITHUB_PERSONAL_TOKEN }}
          policy: myTestRepo/github-actions
          policy-path: security/policies/default.yml
          policy-branch: security
```

**Expected behavior**
Action should checkout the branch defined `policy-branch` 

**Screenshots**
![image](https://user-images.githubusercontent.com/587250/124907219-ca51ed80-dfdf-11eb-9d16-4876bedc36ff.png)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
none
