### ISSUE TITLE
Security Workflow verification

### ISSUE THREAD

**Issue by GeekMasher** [GeekMasher/advanced-security-compliance#34]
### Description

Create a configuration check to verify that repositories are using an approved Actions workflow.

The following items would have to be done:

- [x] #22 
- [ ] Workflow detection
     - Actions used (names can be blank or changed)
- [ ] Parameters matching
     - Actions `with` checking

The following would be a nice to have:

- [ ] Language Validation?
- [ ] Validate SARIF uploading
    - Using: `github/codeql-action/upload-sarif`?

### Propose Solution

```yaml
# ... policies

workflows:
  codeql:
    required: true
    action: github/codeql-action/init
    using:
      config-file: GeekMasher/security-queries/config/codeql.yml@main
      queries: security-extended

  eslint:
    required: true
    upload: true
    languages: [ javascript ]
    action: github/ossar-action
```
