### ISSUE TITLE
Dependabot scan fails with the default policy

### ISSUE THREAD

**Issue by leostolyarov** [GeekMasher/advanced-security-compliance#42]
**Describe the bug**
The Dependabot scan fails with the default policy. The repository does not have any open dependabot alerts, is that why?

**To Reproduce**
1. Run the default action configuration
```
jobs:
  compliance:
    name: Compliance
    runs-on: ubuntu-latest
    steps:
    - name: Advanced Security Compliance Action
      uses: GeekMasher/advanced-security-compliance@v1.5
```

**Expected behavior**
Dependabot violations should be 0.

**Screenshots**
![Screenshot 2021-10-23 at 15 09 13](https://user-images.githubusercontent.com/60515883/138560021-a7d5a09b-409e-4ea6-9c2d-f67c14038681.png)

**Additional context**
The compliance job is run as a reusable workflow from another repository.
