### ISSUE TITLE
Licensing: Condition ID check not implemented

### ISSUE THREAD

**Issue by EwiththeBowtie** [GeekMasher/advanced-security-compliance#57]
**Describe the bug**
Licensing: Condition ID check not implemented
When a licensing policy with only condition ids such as:

```
licensing:
  conditions:
    ids:
      - GPL*
 ```
The GraphQL query on line 56 of `ghascompliace/octokit/dependabot.py` doesn't currently pull the spdxId, the short identifier specified by https://spdx.org/licenses. 
The function `checkViolationAgainstPolicy` in `ghascompliance/policy.py` processes the results. The spdxId included when running `matchContents`, resulting in checks passing when they should fail.

**To Reproduce**
1. Add only a condition check on ids to the licenses policy for a known license in the repository.
2. Run a license check.

**Expected behavior**
License check should fail.

**Comment by GeekMasher** [comment]
@EwiththeBowtie The current default Policy does this using the SPDX license formats. This should pick up all GPL licenses.

[License Policy:](https://github.com/GeekMasher/advanced-security-compliance/blob/main/ghascompliance/defaults/policy.yml#L11-L16)

```yaml
licensing:
  conditions:
    ids:
      - GPL-*
      - LGPL-*
      - AGPL-*
``` 

Have you got an example of the library you are looking for and I can make sure to add it to my test cases?
