### ISSUE TITLE
Unknown Exception was hit, Error: Query failed to run

### ISSUE THREAD

**Issue by hmarnd** [GeekMasher/advanced-security-compliance#61]
**Describe the bug**
Running this action on our workflow we get an error we can't understand.

**To Reproduce**
1. Add action "build-and-test.yaml" to workflow
2. With the following code:
"
advancesecurityComplience:
    runs-on: ubuntu-latest
    name: Advanced Security Complience
    steps:
      - name: Advance Security Compliance Action
        uses: GeekMasher/advanced-security-compliance@v1.6
"
3. See error

Dependabot Results
  Error: {"data": {"repository": {"vulnerabilityAlerts": null}}, "errors": [{"type": "FORBIDDEN", "path": ["repository", "vulnerabilityAlerts"], "extensions": {"saml_failure": false}, "locations": [{"line": 3, "column": 9}], "message": "Resource not accessible by integration"}]}
  Error: Unknown Exception was hit, please repo this to https://github.com/GeekMasher/advanced-security-Compliance
  Error: Query failed to run

**Expected behavior**
Dependabot to block the PR if finds a critical or high risk vulnerability.

**Comment by GeekMasher** [comment]
@hmarnd It looks like the credentials being used don't have permission to access the alerts for your repository.

Try and adding the following where `COMPLIANCE_SECRET` is an access token that can access this resource:

```yml
# Compliance
- name: Advance Security Compliance Action
  uses: GeekMasher/advanced-security-compliance@v1.6.3
  with:
    token: ${{ secrets.COMPLIANCE_SECRET }}
```

You might want to look at [peter-murray/workflow-application-token-action](https://github.com/peter-murray/workflow-application-token-action) to use a GitHub App versus using a GH PAT.
