### ISSUE TITLE
allow list

### ISSUE THREAD

**Issue by lsmith77** [GeekMasher/advanced-security-compliance#69]
### Description

I am trying to define an allow list of licenses but using `*` under `conditions` isn't giving the desired result.

<img width="573" alt="image" src="https://user-images.githubusercontent.com/300279/198064232-3cb50eae-3555-4c23-ad83-41de218d2625.png">

### Propose Solution
if I do the below the `ignores` are not actually ignoring anything as I am still 

```
licensing:
  # The four main rules types to do everything you need to do for all things
  #  compliance

  # Warnings will always occur if the rule applies and continues executing to
  #  other rules.
  warnings:
    ids:
      - other
      - na

  # Ignores are run next so if an ignored rule is hit that matches the level,
  #  it will be skipped
  ignores:
    ids:
      - apache license 2.0
      - bsd 3-clause "new" or "revised" license
      - mit license

  # Conditions will only trigger and raise an error when an exact match is hit
  conditions:
    # note using 'names' here instead of `ids` has the same result
    ids:
      - "*"
```

**Comment by jmservera** [comment]
@romanoroth, @padi-owasp and I were trying to do something similar to get an error on all undetected licenses, and then create an allow list manually. This is because we found many libraries that do not write the license in a standard place, and we want to have a manual allow list for checking licenses.

```yaml
licensing:
  conditions: #to fail
    ids:
      - other
      - na
      - none
  ignores: # what is allowed
    ids:
      - GPL*
      - LGPL*
    names:
      - maven://org.apache.maven.plugins:maven-surefire-plugin*
```
