### ISSUE TITLE
Unknown Exception: Query failed to run by returning code of 502

### ISSUE THREAD

**Issue by agfunderburg10** [GeekMasher/advanced-security-compliance#70]
**Describe the bug**
I receive an Unknown Exception within the Dependency Graph section.

Without a token, I receive this info:

```
Dependency Graph
  Error: Unknown Exception was hit, please repo this to https://github.com/GeekMasher/advanced-security-Compliance
  Error: Query failed to run by returning code of 502. {
      repository(owner: "recurforever", name: "recur-platform") {
          name
          licenseInfo {
              name
          }
          dependencyGraphManifests {
              totalCount
              edges {
                  node {
                      filename
                      dependencies {
                          edges {
                              node {
                                  packageName
                                  packageManager
                                  requirements
                                  repository {
                                      isArchived
                                      isDisabled
                                      isEmpty
                                      isFork
                                      isSecurityPolicyEnabled
                                      isInOrganization
                                      licenseInfo {
                                          name
                                      }
                                  }
                              }
                          }
                      }
                  }
              }
          }
      }
  }
```

With my GITHUB_TOKEN:

```
Dependency Graph
  Error: {
    "data": {
      "repository": {
        "name": "recur-platform",
        "licenseInfo": null,
        "dependencyGraphManifests": {
          "totalCount": 0,
          "edges": []
        }
      }
    },
    "errors": [
      {
        "path": [
          "repository",
          "dependencyGraphManifests"
        ],
        "locations": [
          {
            "line": 7,
            "column": 9
          }
        ],
        "message": "timedout"
      }
    ]
  }
  Error: Unknown Exception was hit, please repo this to https://github.com/GeekMasher/advanced-security-Compliance
  Error: Query failed to run
```

**To Reproduce**
1. Added this as a step in a github workflow with no other steps:
```
  compliance:
    runs-on: [ubuntu-20.04]
    steps:
      - name: Check Compliance
        uses: GeekMasher/advanced-security-compliance@v1.6.3
        with:
          policy-path: ghas_compliance.yml
          argvs: '--disable-dependabot --disable-secret-scanning'
          action: break
          token: ${{ secrets.GITHUB_TOKEN }}
```

**Expected behavior**
The dependency graph would successfully complete.
