### ISSUE TITLE
Rule matching with IDs and Names

### ISSUE THREAD

**Issue by GeekMasher** [GeekMasher/advanced-security-compliance#9]
### Description

We need the ability to create wildcard support to find conditions that match. to catch more generally rule

### Examples

```yaml
licensing:
  conditions:
    ids:
      - GPL-*
```

### Items

- [x] Wildcards for Rules
    - [x] IDs
    - [x] Names
